/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eu.ricardocabral.fileprocessor;

import eu.ricardocabral.fileprocessor.exception.ApplicationException;
import eu.ricardocabral.fileprocessor.processor.TextProcessor;
import org.junit.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {

    private static final String SAMPLE_FILE_NAME = "sample_story.txt";
    private static final Path SAMPLE_FILE = Paths.get("src", "test", "resources", SAMPLE_FILE_NAME);


    @Test(expected = ApplicationException.class)
    public void shouldTryToCallApplicationWithNullArgumentsAndThrowAnException(){
        App.main(null);
    }

    @Test(expected = ApplicationException.class)
    public void shouldTryToCallApplicationWithMoreThanOneArgumentAndThroException(){

        App.main(new String[]{"directory1", "directory2"});
    }

    @Test(expected = ApplicationException.class)
    public void shouldTryToReadInvalidDirectoryAndThrowsException(){
        App.main(new String[]{"/usr/invalid/directory"});
    }

    @Test
    public void shouldReadFileAndProcessIt() throws IOException {

        TextProcessor textProcessor = new TextProcessor();
        textProcessor.processFile(SAMPLE_FILE);

    }

}
